// Generated by CoffeeScript 1.6.1
var conf, fs, load, logger, loggerTransports, path, winston;

fs = require("fs");

path = require("path");

winston = require("winston");

conf = {};

load = function() {
  var file;
  file = (function() {
    switch (process.env.NODE_ENV) {
      case "development":
        return "dev.json";
      case "preproduction":
        return "preprod.json";
      default:
        return "prod.json";
    }
  })();
  return conf = JSON.parse(fs.readFileSync(path.resolve("conf", file)));
};

loggerTransports = function() {
  if (process.env.NODE_ENV === "development") {
    return [
      new winston.transports.Console({
        colorize: true
      })
    ];
  } else {
    return [
      new winston.transports.Console({
        colorize: true
      }), new winston.transports.DailyRotateFile({
        filename: path.resolve("logs", "./metrics.log")
      })
    ];
  }
};

logger = new winston.Logger({
  transports: loggerTransports()
});

exports.getConf = function() {
  return conf;
};

exports.getLogger = function() {
  return logger;
};

exports.loggerTransports = loggerTransports;

exports.load = load;
